FROM ubuntu:22.04

# 対話モード抑止（apt install時のダイアログ回避）
ENV DEBIAN_FRONTEND=noninteractive

# 基本的な開発ツールをインストール
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://ftp.jaist.ac.jp/pub/Linux/ubuntu/|g' /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    gnupg \
    software-properties-common \
    ansible \
    openssh-client \
    sudo \    
    python3 \
    python3-pip \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Terraform v1.6.6 をインストール
RUN curl -fsSL https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip \
    && unzip terraform.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform.zip

# Azure CLI をインストール
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

# ユーザー追加（VSCodeが使いやすいように）
RUN useradd -ms /bin/bash devuser && echo "devuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER devuser
WORKDIR /home/devuser
